const assignments = [
  { 
    "_id": "A101", 
    "title": "A1", 
    "name": "Propulsion Assignment", 
    "course": "RS101",
    "description": "The assignment is available online\n\nSubmit a link to the landing page of your Web application running on Netlify.\n\nThe landing page should include the following:\n• Your full name and section\n• Links to each of the lab assignments\n• Link to the Kambas application\n• Links to all relevant source code repositories\n\nThe Kambas application should include a link to navigate back to the landing page.",
    "points": 100,
    "assignmentGroup": "ASSIGNMENTS",
    "displayGradeAs": "Percentage",
    "submissionType": "Online",
    "onlineEntryOptions": {
      "textEntry": false,
      "websiteUrl": true,
      "mediaRecordings": false,
      "studentAnnotation": false,
      "fileUploads": false
    },
    "dueDate": "2024-05-13",
    "dueTime": "23:59",
    "availableFromDate": "2024-05-06",
    "availableFromTime": "00:01",
    "untilDate": "",
    "untilTime": ""
  },
  { 
    "_id": "A102", 
    "title": "A2", 
    "name": "Combustion Analysis", 
    "course": "RS101",
    "description": "Analyze the combustion processes in rocket engines and submit a detailed report covering fuel efficiency, combustion stability, and performance optimization.",
    "points": 100,
    "assignmentGroup": "ASSIGNMENTS",
    "displayGradeAs": "Percentage",
    "submissionType": "Online",
    "onlineEntryOptions": {
      "textEntry": true,
      "websiteUrl": false,
      "mediaRecordings": false,
      "studentAnnotation": false,
      "fileUploads": true
    },
    "dueDate": "2024-05-20",
    "dueTime": "23:59",
    "availableFromDate": "2024-05-13",
    "availableFromTime": "00:01",
    "untilDate": "",
    "untilTime": ""
  },
  { 
    "_id": "A103", 
    "title": "A3", 
    "name": "Nozzle Design Project", 
    "course": "RS101",
    "description": "Design and optimize a rocket nozzle for specific mission requirements. Include CAD models, performance calculations, and design rationale.",
    "points": 150,
    "assignmentGroup": "PROJECTS",
    "displayGradeAs": "Letter",
    "submissionType": "Online",
    "onlineEntryOptions": {
      "textEntry": true,
      "websiteUrl": false,
      "mediaRecordings": true,
      "studentAnnotation": false,
      "fileUploads": true
    },
    "dueDate": "2024-05-27",
    "dueTime": "23:59",
    "availableFromDate": "2024-05-20",
    "availableFromTime": "00:01",
    "untilDate": "",
    "untilTime": ""
  },
  { 
    "_id": "A201", 
    "title": "Q1", 
    "name": "Aerodynamics Quiz", 
    "course": "RS102",
    "description": "Quiz covering fundamental aerodynamic principles, fluid dynamics, and airfoil design concepts.",
    "points": 50,
    "assignmentGroup": "QUIZZES",
    "displayGradeAs": "Percentage",
    "submissionType": "Online",
    "onlineEntryOptions": {
      "textEntry": true,
      "websiteUrl": false,
      "mediaRecordings": false,
      "studentAnnotation": false,
      "fileUploads": false
    },
    "dueDate": "2024-05-15",
    "dueTime": "23:59",
    "availableFromDate": "2024-05-10",
    "availableFromTime": "00:01",
    "untilDate": "",
    "untilTime": ""
  },
  { 
    "_id": "A202", 
    "title": "A1", 
    "name": "Flow Analysis", 
    "course": "RS102",
    "description": "Conduct computational fluid dynamics analysis of various airfoil configurations and submit detailed results.",
    "points": 100,
    "assignmentGroup": "ASSIGNMENTS",
    "displayGradeAs": "Percentage",
    "submissionType": "Online",
    "onlineEntryOptions": {
      "textEntry": true,
      "websiteUrl": false,
      "mediaRecordings": false,
      "studentAnnotation": false,
      "fileUploads": true
    },
    "dueDate": "2024-05-22",
    "dueTime": "23:59",
    "availableFromDate": "2024-05-15",
    "availableFromTime": "00:01",
    "untilDate": "",
    "untilTime": ""
  },
  { 
    "_id": "A203", 
    "title": "A2", 
    "name": "Heating Analysis", 
    "course": "RS102",
    "description": "Analyze aerodynamic heating effects on spacecraft during atmospheric entry and design thermal protection systems.",
    "points": 120,
    "assignmentGroup": "ASSIGNMENTS",
    "displayGradeAs": "Percentage",
    "submissionType": "Online",
    "onlineEntryOptions": {
      "textEntry": true,
      "websiteUrl": false,
      "mediaRecordings": false,
      "studentAnnotation": false,
      "fileUploads": true
    },
    "dueDate": "2024-05-29",
    "dueTime": "23:59",
    "availableFromDate": "2024-05-22",
    "availableFromTime": "00:01",
    "untilDate": "",
    "untilTime": ""
  },
  { 
    "_id": "A301", 
    "title": "A1", 
    "name": "Structural Design Task", 
    "course": "RS103",
    "description": "Design spacecraft structural components using finite element analysis and material selection criteria.",
    "points": 100,
    "assignmentGroup": "ASSIGNMENTS",
    "displayGradeAs": "Percentage",
    "submissionType": "Online",
    "onlineEntryOptions": {
      "textEntry": true,
      "websiteUrl": false,
      "mediaRecordings": false,
      "studentAnnotation": false,
      "fileUploads": true
    },
    "dueDate": "2024-05-18",
    "dueTime": "23:59",
    "availableFromDate": "2024-05-11",
    "availableFromTime": "00:01",
    "untilDate": "",
    "untilTime": ""
  },
  { 
    "_id": "A302", 
    "title": "A2", 
    "name": "Orbital Calculations", 
    "course": "RS103",
    "description": "Calculate orbital parameters, transfer trajectories, and mission planning for various space missions.",
    "points": 100,
    "assignmentGroup": "ASSIGNMENTS",
    "displayGradeAs": "Percentage",
    "submissionType": "Online",
    "onlineEntryOptions": {
      "textEntry": true,
      "websiteUrl": false,
      "mediaRecordings": false,
      "studentAnnotation": false,
      "fileUploads": true
    },
    "dueDate": "2024-05-25",
    "dueTime": "23:59",
    "availableFromDate": "2024-05-18",
    "availableFromTime": "00:01",
    "untilDate": "",
    "untilTime": ""
  },
  { 
    "_id": "A303", 
    "title": "E1", 
    "name": "Systems Engineering Exam", 
    "course": "RS103",
    "description": "Comprehensive exam covering spacecraft systems engineering, integration, and mission design principles.",
    "points": 200,
    "assignmentGroup": "EXAMS",
    "displayGradeAs": "Letter",
    "submissionType": "In-Person",
    "onlineEntryOptions": {
      "textEntry": false,
      "websiteUrl": false,
      "mediaRecordings": false,
      "studentAnnotation": false,
      "fileUploads": false
    },
    "dueDate": "2024-06-01",
    "dueTime": "23:59",
    "availableFromDate": "2024-05-25",
    "availableFromTime": "00:01",
    "untilDate": "",
    "untilTime": ""
  }
];

export default assignments;